stages:
  - build
  - sast
  - test
  - rollout
  - rollout-old

include:
 - project: "koibanx/ops/automation/templates-gitlab"
   ref: main
   file:
      - "Jobs/Docker.gitlab-ci.yml"
#      - "Jobs/Docker-Worker.gitlab-ci.yml"
#      - "Jobs/Docker-AWSandGCP.gitlab-ci.yml"
#      - "Jobs/Docker-Worker-AWSandGCP.gitlab-ci.yml"
      - "Jobs/Rollout-K8S.gitlab-ci.yml"
#      - "Jobs/Rollout-K8S_OldDevelop.gitlab-ci.yml"
      - "Workflows/Docker.gitlab-ci.yml"
      - "Workflows/Rules-Environments.gitlab-ci.yml"
      - "Security/Container-Scanning.gitlab-ci.yml"
      - "Security/Secret-Detection.gitlab-ci.yml"
      - "Security/SAST.gitlab-ci.yml"